trigger:
- master

pool:
  name: default
  demands:
    - Agent.Name -equals Agent-01

jobs:
- job: job1
  steps:
  - script: echo Job1 - Hi From Job 1
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: job2
  dependsOn: job1
  steps:
  - script: echo Job2 - Hellow for Job 2
- job: job3
  dependsOn: job2
  steps:
  - script: echo Job3 - Hola for Job 3