trigger:
- master

stages:
- stage:
  jobs:
  - job:
    steps:
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

#==== backup ===#
# trigger:
# - master

# pool:
#   name: default
#   demands:
#     - Agent.OS -equals Linux

# stages:
# - stage: Build
#   variables:
#      env: dharani
#      dharani: adk
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo Build FirstJob "$(pipelinelevelvariable)"
#     - bash: echo $(env) is none other than $(dharani)

#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob with $(env)

# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo DevDeployJob
  
# - stage: QADeploy
#   dependsOn: Build
#   jobs:
#   - job: QADeploy
#     steps:
#     - bash: echo QADeployJob

# - stage: ProdDeploy
#   dependsOn:
#   - QADeploy
#   - DevDeploy
#   jobs:
#   - job: ProdDeploy
#     steps:
#     - bash: echo Production Deploy
