trigger:
- master

strategy:
  matrix:
    linux:
       operatingSystem: "ubuntu-latest"
    mac:
       operatingSystem: "macos-latest"

pool:
 vmImage: $(operatingSystem)

steps:
- script: echo this is running in $(operatingSystem)
  displayName: 'Run a one-line script'

